# Find the Difference
'''
Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:
s = "abcd"
t = "adecb"
output = "e"
'''

#####################################################################
# My solution
# 54 / 54 test cases passed.
# Status: Accepted
# Runtime: 28 ms
# Memory Usage: 13.9 MB
#####################################################################
class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        s2 = list(s)
        t2 = list(t)

        s2.sort()
        t2.sort()
        
        for i in range(len(s2)):
            if s2[i] != t2[i]:
                return t2[i]
            
        return t2[len(t2)-1]


#####################################################################
# Fastest solution (12ms)
#####################################################################
'''
class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        for i in range(97,97+26):
            if s.count(chr(i))!=t.count(chr(i)):
                return chr(i)
'''